image : maven:3.8.5-jdk-11

stages:
    - build
before_script:
    - pwd
build_job:
    stage: build
    only:
        - pushes
    script:
        - mvn --batch-mode verify sonar:sonar -Dsonar.host.url=http://srvoptiic3.optimissa.into:9100/ -Dsonar.login=squ_b59e2f974bdf336032a1c96acac46ede78c64bfd
    tags:
        - docker
